version: '3.9'

services:
  node:
    image: "node:lts-alpine"
    user: node
    working_dir: /home/node/app
    volumes:
      - ${PWD-.}:/home/node/app
    ports:
      - 3008:3000
    command: sh -c "npm install && npm run dev"